// This file had been automatically generated by utility "github.com/xaionaro-go/atomicmap/internal/benchmarkCodeGen"

package atomicmap

import (
	"testing"

	benchmark "github.com/xaionaro-go/atomicmap/internal/benchmarkRoutines"
)

func TestMap(t *testing.T) {
	benchmark.DoTest(t, NewWithArgs)
}

func Benchmark_atomicmap_Set_intKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 128, 16, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 128, 16, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 128, 16, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 128, 16, "string")
}

func Benchmark_atomicmap_Set_intKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 1024, 16, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 1024, 16, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 1024, 16, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 1024, 16, "string")
}

func Benchmark_atomicmap_Set_intKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 65536, 512, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 65536, 512, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 65536, 512, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 65536, 512, "string")
}

func Benchmark_atomicmap_Set_intKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 4194304, 65536, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 4194304, 65536, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 4194304, 65536, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 4194304, 65536, "string")
}

func Benchmark_atomicmap_Set_intKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 16777216, 65536, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 16777216, 65536, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 16777216, 65536, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 16777216, 65536, "string")
}

func Benchmark_atomicmap_Set_intKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 16777216, 1048576, "int")
}

func BenchmarkParallel_atomicmap_Set_intKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 16777216, 1048576, "int")
}

func Benchmark_atomicmap_Set_stringKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, 16777216, 1048576, "string")
}

func BenchmarkParallel_atomicmap_Set_stringKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, 16777216, 1048576, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 128, 16, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 128, 16, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 128, 16, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 128, 16, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 1024, 16, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 1024, 16, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 1024, 16, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 1024, 16, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 65536, 512, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 65536, 512, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 65536, 512, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 65536, 512, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 4194304, 65536, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 4194304, 65536, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 4194304, 65536, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 4194304, 65536, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 16777216, 65536, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 16777216, 65536, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 16777216, 65536, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 16777216, 65536, "string")
}

func Benchmark_atomicmap_Get_intKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 16777216, 1048576, "int")
}

func BenchmarkParallel_atomicmap_Get_intKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 16777216, 1048576, "int")
}

func Benchmark_atomicmap_Get_stringKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, 16777216, 1048576, "string")
}

func BenchmarkParallel_atomicmap_Get_stringKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, 16777216, 1048576, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 128, 16, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize128_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 128, 16, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 1024, 16, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize1024_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 1024, 16, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 65536, 512, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize65536_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 65536, 512, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 4194304, 65536, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize4194304_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 4194304, 65536, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 16777216, 65536, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize16777216_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 16777216, 65536, "string")
}

func Benchmark_atomicmap_Unset_intKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 16777216, 1048576, "int")
}

func Benchmark_atomicmap_Unset_stringKeyType_blockSize16777216_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, 16777216, 1048576, "string")
}
