
// This file had been automatically generated by utility "git.dx.center/trafficstars/testJob0/internal/benchmarkCodeGen"

package stupidMap

import (
	"testing"

	benchmark "git.dx.center/trafficstars/testJob0/internal/benchmarkRoutines"
)

func BenchmarkSet_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 16, "int")
}

func BenchmarkSet_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 16, "string")
}

func BenchmarkSet_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 512, "int")
}

func BenchmarkSet_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 512, "string")
}

func BenchmarkSet_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkSet_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkSet_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkSet_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 0, 1048576, "string")
}

func BenchmarkReSet_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 16, "int")
}

func BenchmarkReSet_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 16, "string")
}

func BenchmarkReSet_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 512, "int")
}

func BenchmarkReSet_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 512, "string")
}

func BenchmarkReSet_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkReSet_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkReSet_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkReSet_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 0, 1048576, "string")
}

func BenchmarkGet_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 16, "int")
}

func BenchmarkGet_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 16, "string")
}

func BenchmarkGet_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 512, "int")
}

func BenchmarkGet_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 512, "string")
}

func BenchmarkGet_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkGet_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkGet_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkGet_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 0, 1048576, "string")
}

func BenchmarkGetMiss_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 16, "int")
}

func BenchmarkGetMiss_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 16, "string")
}

func BenchmarkGetMiss_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 512, "int")
}

func BenchmarkGetMiss_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 512, "string")
}

func BenchmarkGetMiss_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkGetMiss_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkGetMiss_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkGetMiss_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 0, 1048576, "string")
}

func BenchmarkUnset_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 16, "int")
}

func BenchmarkUnset_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 16, "string")
}

func BenchmarkUnset_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 512, "int")
}

func BenchmarkUnset_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 512, "string")
}

func BenchmarkUnset_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkUnset_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkUnset_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkUnset_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 0, 1048576, "string")
}

func BenchmarkUnsetMiss_intKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 16, "int")
}

func BenchmarkUnsetMiss_stringKeyType_blockSize0_keyAmount16(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 16, "string")
}

func BenchmarkUnsetMiss_intKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 512, "int")
}

func BenchmarkUnsetMiss_stringKeyType_blockSize0_keyAmount512(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 512, "string")
}

func BenchmarkUnsetMiss_intKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 65536, "int")
}

func BenchmarkUnsetMiss_stringKeyType_blockSize0_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 65536, "string")
}

func BenchmarkUnsetMiss_intKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 1048576, "int")
}

func BenchmarkUnsetMiss_stringKeyType_blockSize0_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 0, 1048576, "string")
}
