// This file had been automatically generated by utility "github.com/xaionaro-go/atomicmap/internal/benchmarkCodeGen"

package builtinSyncMap

import (
	"testing"

	"github.com/xaionaro-go/atomicmap/hasher"
	benchmark "github.com/xaionaro-go/atomicmap/internal/benchmarkRoutines"
)

func Benchmark_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 16, "int")
}

func BenchmarkParallel_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 16, "int")
}

func Benchmark_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 16, "string")
}

func BenchmarkParallel_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 16, "string")
}

func Benchmark_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 512, "int")
}

func BenchmarkParallel_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 512, "int")
}

func Benchmark_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 512, "string")
}

func BenchmarkParallel_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 512, "string")
}

func Benchmark_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 65536, "int")
}

func BenchmarkParallel_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 65536, "int")
}

func Benchmark_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 65536, "string")
}

func BenchmarkParallel_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 65536, "string")
}

func Benchmark_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 1048576, "int")
}

func BenchmarkParallel_builtinSyncMap_Set_intKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 1048576, "int")
}

func Benchmark_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 1048576, "string")
}

func BenchmarkParallel_builtinSyncMap_Set_stringKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfSet(b, NewWithArgs, hasher.New(), 0, 1048576, "string")
}

func Benchmark_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 16, "int")
}

func BenchmarkParallel_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 16, "int")
}

func Benchmark_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 16, "string")
}

func BenchmarkParallel_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 16, "string")
}

func Benchmark_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 512, "int")
}

func BenchmarkParallel_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 512, "int")
}

func Benchmark_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 512, "string")
}

func BenchmarkParallel_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 512, "string")
}

func Benchmark_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 65536, "int")
}

func BenchmarkParallel_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 65536, "int")
}

func Benchmark_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 65536, "string")
}

func BenchmarkParallel_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 65536, "string")
}

func Benchmark_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 1048576, "int")
}

func BenchmarkParallel_builtinSyncMap_Get_intKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 1048576, "int")
}

func Benchmark_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 1048576, "string")
}

func BenchmarkParallel_builtinSyncMap_Get_stringKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoParallelBenchmarkOfGet(b, NewWithArgs, hasher.New(), 0, 1048576, "string")
}

func Benchmark_builtinSyncMap_Unset_intKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 16, "int")
}

func Benchmark_builtinSyncMap_Unset_stringKeyType_blockSize0_keyAmount16_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 16, "string")
}

func Benchmark_builtinSyncMap_Unset_intKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 512, "int")
}

func Benchmark_builtinSyncMap_Unset_stringKeyType_blockSize0_keyAmount512_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 512, "string")
}

func Benchmark_builtinSyncMap_Unset_intKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 65536, "int")
}

func Benchmark_builtinSyncMap_Unset_stringKeyType_blockSize0_keyAmount65536_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 65536, "string")
}

func Benchmark_builtinSyncMap_Unset_intKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 1048576, "int")
}

func Benchmark_builtinSyncMap_Unset_stringKeyType_blockSize0_keyAmount1048576_trueThreadSafety(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewWithArgs, hasher.New(), 0, 1048576, "string")
}
