// This file had been automatically generated by utility "git.dx.center/trafficstars/testJob0/internal/benchmarkCodeGen"

package cgoTsearch

import (
	"testing"

	benchmark "git.dx.center/trafficstars/testJob0/internal/benchmarkRoutines"
)

func TestMap(t *testing.T) {
	benchmark.DoTest(t, NewHashMap)
}

func BenchmarkSet_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkSet_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfSet(b, NewHashMap, 1048576, 1048576, "int")
}

func BenchmarkReSet_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkReSet_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfReSet(b, NewHashMap, 1048576, 1048576, "int")
}

func BenchmarkGet_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkGet_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGet(b, NewHashMap, 1048576, 1048576, "int")
}

func BenchmarkGetMiss_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkGetMiss_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfGetMiss(b, NewHashMap, 1048576, 1048576, "int")
}

func BenchmarkUnset_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkUnset_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnset(b, NewHashMap, 1048576, 1048576, "int")
}

func BenchmarkUnsetMiss_intKeyType_blockSize1048576_keyAmount65536(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 1048576, 65536, "int")
}

func BenchmarkUnsetMiss_intKeyType_blockSize1048576_keyAmount1048576(b *testing.B) {
	benchmark.DoBenchmarkOfUnsetMiss(b, NewHashMap, 1048576, 1048576, "int")
}
